###################
# FOR LOCAL DEVELOPMENT
###################
FROM node:20.11-alpine

RUN apk update && apk add git \
  && rm -vrf /var/cache/apk/*

COPY . /workspace

WORKDIR /workspace

EXPOSE 3333
